app = "fly-scraper"
primary_region = "atl"

[build]

[env]
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
  source = "scraper_volume"
  destination = "/app/persist"
