app = "fly-scraper"
primary_region = "atl"

[build]

[env]
PORT = "8080"

[mounts]
  source = "data"
  destination = "/data"


[experimental]
auto_rollback = true

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
